kind: Service
apiVersion: v1
metadata:
  name: mywebapp-service
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
  - protocol: TCP
    port: 80
    nodePort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
  labels:
     app: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: $DOCKER_IMAGE_NAME$BUILD_NUMBER
        ports:
        - containerPort: 8080
